name: TM Bot

on:
  schedule:
    # 09:00 GMT+7
    - cron: '0 2 * * *'

    # 15:00 GMT+7
    - cron: '0 8 * * *'

    # 22:30 GMT+7
    - cron: '30 15 * * *'

jobs:
  consolidate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run consolidation
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TM_DAILY_DATABASE_ID: ${{ secrets.TM_DAILY_DATABASE_ID }}
        run: |
          python daily_consolidation.py
